import "../../assets/style/account.scss";
import { FormInput } from "../../components/FormInput";
import { AccountPageUpdatePassword } from "../../components/account/AccountPageUpdatePassword";
import { RootState } from "../../store/store";
import { useAppSelector } from "../../utils/hooks/store";

const AccountPage = () => {
  const { user } = useAppSelector((state: RootState) => state.auth);

  return (
    <div className="account-container">
      <div className="row align-items-center">
        <div className="col-12 col-xl-2 d-flex flex-row flex-lg-column">
          <img src={user?.avatar} alt="avatar" className="avatar border rounded-circle" width={180} />
          <small className="text-center text-muted mt-3">This is an autogenerated unique avatar for your account</small>
        </div>
        <div className="col-12 col-xl-10 mt-5 mt-xl-0">
          <div className="d-flex flex-column flex-xl-row gap-3 mb-4">
            <FormInput label="name" name="name" disabled={true} defaultValue={user?.name} className="w-100" />
            <FormInput
              label="lastname"
              name="lastname"
              disabled={true}
              defaultValue={user?.lastname}
              className="w-100"
            />
            <FormInput
              label="username"
              name="username"
              disabled={true}
              defaultValue={user?.username}
              className="w-100"
            />
            <FormInput label="email" name="email" disabled={true} defaultValue={user?.email} className="w-100" />
          </div>
          <AccountPageUpdatePassword />
        </div>
      </div>
    </div>
  );
};

export default AccountPage;
